// Generated by CoffeeScript 1.4.0
var app, port, server, io;

server = require('./.app');


server.listen(3000, function() {
  return console.log("Listening on 3000\n Press CTRL-C to stop server.");
});


